[package]
name = "react_scoped_css"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
md5 = "0.7.0"
regex = "1.10.4"
serde = "1"
serde_json = "1.0.115"
serde_regex = "1.1.0"
swc_common = "0.33.22"
swc_core = { version = "0.90.*", features = ["ecma_plugin_transform"] }
swc_ecma_parser = "0.143.12"
swc_ecma_transforms = "0.229.18"

[dev-dependencies]
swc_ecma_transforms_testing = "0.140.18"
testing = "0.35.22"
